// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOIJvLcaSiguj0qklTIRsYnxwrSMdMj4k',
    appId: '1:233874385422:web:7421144530d54b5fd82a5f',
    messagingSenderId: '233874385422',
    projectId: 'agilib-29cf3',
    authDomain: 'agilib-29cf3.firebaseapp.com',
    storageBucket: 'agilib-29cf3.firebasestorage.app',
    measurementId: 'G-Y14GREPQXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6jiVv_Ylk9xSSbxDl0hHeOv1K_B3ank',
    appId: '1:233874385422:android:6b03549c20f6266ad82a5f',
    messagingSenderId: '233874385422',
    projectId: 'agilib-29cf3',
    storageBucket: 'agilib-29cf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlk8SeOI28fJZ_yQH14atZwTseYA1aJt4',
    appId: '1:233874385422:ios:eb14a87e814a9165d82a5f',
    messagingSenderId: '233874385422',
    projectId: 'agilib-29cf3',
    storageBucket: 'agilib-29cf3.firebasestorage.app',
    iosBundleId: 'com.example.agilib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlk8SeOI28fJZ_yQH14atZwTseYA1aJt4',
    appId: '1:233874385422:ios:eb14a87e814a9165d82a5f',
    messagingSenderId: '233874385422',
    projectId: 'agilib-29cf3',
    storageBucket: 'agilib-29cf3.firebasestorage.app',
    iosBundleId: 'com.example.agilib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOIJvLcaSiguj0qklTIRsYnxwrSMdMj4k',
    appId: '1:233874385422:web:610119e6dd81eeafd82a5f',
    messagingSenderId: '233874385422',
    projectId: 'agilib-29cf3',
    authDomain: 'agilib-29cf3.firebaseapp.com',
    storageBucket: 'agilib-29cf3.firebasestorage.app',
    measurementId: 'G-SCPFNJ5MT6',
  );
}
